
#' Patient Facts -- Output Generation
#'
#' Using the tabular output generated by `pf_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `pf_process`
#'
#'   Note any patient-level results generated are not intended to be used with this function.
#'
#' @param output *string* || defaults to `NULL`
#'
#'   The name of the numerical variable from `process_output` that should be used to
#'   generate the plot. This input is required for the following checks:
#'   - `Single Site, Exploratory, Cross-Sectional`
#'   - `Multi-Site, Exploratory, Cross-Sectional`
#'   - `Single Site, Anomaly Detection, Cross-Sectional`
#'   - `Single Site, Exploratory Longitudinal`
#'   - `Multi Site Exploratory Longitudinal`
#'
#' @param date_breaks_str *string* || defaults to `1 year`
#'
#'   A string that controls the time period division on the x-axis ('1 year', '3 months', etc).
#'   This parameter is only required for the `Single Site, Exploratory, Longitudinal` check.
#'
#' @param domain_filter *string* || defaults to `NULL`
#'
#'   A string indicating the domain of interest for plotting. This parameter
#'   is required for the following checks:
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'   - `Multi-Site, Anomaly Detection, Longitudinal`
#'
#' @param visit_filter *string* || defaults to `NULL`
#'
#'   A string indicating the visit type of interest for plotting. This parameter
#'   is required for the following checks:
#'   - `Multi-Site, Anomaly Detection, Cross-Sectional`
#'   - `Single Site, Anomaly Detection, Longitudinal`
#'   - `Multi-Site, Anomaly Detection, Longitudinal`
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `pf_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-pf_process_output.R
#'
#' @export
#'

pf_output <- function(process_output,
                      output = NULL,
                      #facet = NULL,
                      date_breaks_str = '1 year',
                      domain_filter = NULL,
                      visit_filter = NULL,
                      large_n = FALSE,
                      large_n_sites = NULL){

  # extract output_function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  ## Run output functions
  if(output_function == 'pf_ms_anom_cs'){
    pf_output <- pf_ms_anom_cs(data_tbl = process_output,
                               facet = facet,
                               visit_filter = visit_filter,
                               large_n = large_n,
                               large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_anom_cs'){
    pf_output <- pf_ss_anom_cs(data_tbl = process_output,
                               output = output,
                               facet = facet)
  }else if(output_function == 'pf_ms_exp_cs'){
    pf_output <- pf_ms_exp_cs(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_exp_cs'){
    pf_output <- pf_ss_exp_cs(data_tbl = process_output,
                              output = output,
                              facet = facet)
  }else if(output_function == 'pf_ms_anom_la'){
    pf_output <- pf_ms_anom_la(process_output = process_output,
                               domain_filter = domain_filter,
                               visit_filter = visit_filter,
                               large_n = large_n,
                               large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_anom_la'){
    pf_output <- pf_ss_anom_la(data_tbl = process_output,
                               #output = output,
                               facet = facet,
                               visit_filter = visit_filter,
                               domain_filter = domain_filter)
  }else if(output_function == 'pf_ms_exp_la'){
    pf_output <- pf_ms_exp_la(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_exp_la'){
    pf_output <- pf_ss_exp_la(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              date_breaks_str = date_breaks_str)
  }else(cli::cli_abort('Please enter a valid output_function for this check type.'))

  return(pf_output)
}
