
#' Patient Facts -- Output Generation
#'
#' Using the tabular output generated by `pf_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* | the summary dataframe output by the `pf_process` function.
#'
#' Note any patient-level results generated are not intended to be used with this function.
#' @param output *string* | the numerical variable in `process_output` that should be used to generate the graph
#' @param date_breaks_str *string* | for `ss_exp_la` only, a string that informs the program how the
#'                        time period should be divided (i.e. '1 year', '3 months', etc). Defaults to 1 year.
#' @param domain_filter *string* | the domain to which the graph should be filtered; used for `ms_anom_la` & `ss_anom_la`
#' @param visit_filter *string* | the visit type to which the graph should be filtered; used for `ms_anom_cs`, `ms_anom_la`, & `ss_anom_la`
#' @param large_n *boolean* | for multi site analyses, a boolean indicating whether the large N visualization, intended for a high
#'                volume of sites, should be used; defaults to FALSE
#' @param large_n_sites *vector* | when large_n is TRUE, a vector of site names that can optionally generate a filtered visualization
#'
#' @return a graph summarizing the data output by `pf_process`; see individual output functions for specific details
#'
#' @example inst/example-pf_process_output.R
#'
#' @export
#'

pf_output <- function(process_output,
                      output,
                      #facet = NULL,
                      date_breaks_str = '1 year',
                      domain_filter = NULL,
                      visit_filter = NULL,
                      large_n = FALSE,
                      large_n_sites = NULL){

  # extract output_function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()

  if('age_grp' %in% colnames(process_output)){facet <- 'age_grp'}else{facet <- NULL}

  ## Run output functions
  if(output_function == 'pf_ms_anom_cs'){
    pf_output <- pf_ms_anom_cs(data_tbl = process_output,
                               facet = facet,
                               visit_filter = visit_filter,
                               large_n = large_n,
                               large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_anom_cs'){
    pf_output <- pf_ss_anom_cs(data_tbl = process_output,
                               output = output,
                               facet = facet)
  }else if(output_function == 'pf_ms_exp_cs'){
    pf_output <- pf_ms_exp_cs(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_exp_cs'){
    pf_output <- pf_ss_exp_cs(data_tbl = process_output,
                              output = output,
                              facet = facet)
  }else if(output_function == 'pf_ms_anom_la'){
    pf_output <- pf_ms_anom_la(process_output = process_output,
                               domain_filter = domain_filter,
                               visit_filter = visit_filter,
                               large_n = large_n,
                               large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_anom_la'){
    pf_output <- pf_ss_anom_la(data_tbl = process_output,
                               #output = output,
                               facet = facet,
                               visit_filter = visit_filter,
                               domain_filter = domain_filter)
  }else if(output_function == 'pf_ms_exp_la'){
    pf_output <- pf_ms_exp_la(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_function == 'pf_ss_exp_la'){
    pf_output <- pf_ss_exp_la(data_tbl = process_output,
                              output = output,
                              facet = facet,
                              date_breaks_str = date_breaks_str)
  }else(cli::cli_abort('Please enter a valid output_function for this check type.'))

  return(pf_output)
}
